[project]
name = "mmf_sa"
version = "0.0.1"
description = "Many Models Forecasting (MMF) Statistical Analysis Package"
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "datasetsforecast==0.0.8",
    "fugue==0.9.0",
    "Jinja2==3.1.2",
    "kaleido==0.2.1",
    "lightgbm==4.1.0",
    "matplotlib==3.7.0",
    "missingno==0.5.2",
    "mlflow-skinny==2.9.2",
    "neuralforecast==1.7.2",
    "numpy==1.23.5",
    "omegaconf==2.3.0",
    "pandas==1.5.3",
    "plotly==5.9.0",
    "pyarrow==8.0.0",
    "pyarrow-hotfix==0.5",
    "pyspark==3.5.0",
    "scikit-learn==1.1.1",
    "scipy==1.10.0",
    "seaborn==0.12.2",
    "sktime==0.29.0",
    "statsforecast==1.7.4",
    "tbats==1.1.3",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "setuptools",
    "wheel",
    "black",
    "flake8",
    "mypy",
    "isort",
]

[tool.hatch.envs.full]
features = ["dev"]

[tool.hatch.metadata]
databricks-runtime-cpu = "14.3.x-cpu-ml-scala2.12"
databricks-runtime-gpu = "14.3.x-gpu-ml-scala2.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "mmf_sa/",
]
exclude = [
    "tests/",
    "docs/",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    ".git",
    ".gitignore",
    ".vscode",
    ".idea",
]

[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
ignore_missing_imports = true
strict_optional = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]